services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: iiita_helpdesk
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./server
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=iiita_helpdesk
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./server:/app

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app

volumes:
  db_data: